# .github/workflows/deploy/app_deploy.yml

name: App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in app directory
        id: check_app
        run: |
         echo "app pipleine"
