name: BFF Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here
      - name: Deploy BFF
        run: echo "Deploying BFF..."
