name: Calypso CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Shared checkout step for all jobs
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  # App pipeline - runs for changes in app or entire Calypso repo
  app:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Check for changes in app or Calypso
        id: check_app
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^(app/|Calypso/)'; then
            echo "changes_in_app=true" >> $GITHUB_ENV
          else
            echo "changes_in_app=false" >> $GITHUB_ENV
          fi
      - name: Run app pipeline
        if: env.changes_in_app == 'true'
        run: echo "Running app pipeline due to changes in app or Calypso"
        # Add your app pipeline steps here (tests, builds, etc.)

  # BFF pipeline - runs for changes in bff or entire Calypso repo
  bff:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Check for changes in bff or Calypso
        id: check_bff
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^(bff/|Calypso/)'; then
            echo "changes_in_bff=true" >> $GITHUB_ENV
          else
            echo "changes_in_bff=false" >> $GITHUB_ENV
          fi
      - name: Run bff pipeline
        if: env.changes_in_bff == 'true'
        run: echo "Running bff pipeline due to changes in bff or Calypso"
        # Add your bff pipeline steps here (tests, builds, etc.)
