name: Calypso CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.commits && contains(join(github.event.commits.*.modified, ','), 'app/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: app

      - name: Print directory
        run: echo "Changes detected in app directory"

  bff:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.commits && contains(join(github.event.commits.*.modified, ','), 'bff/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: bff

      - name: Print directory
        run: echo "Changes detected in bff directory"
