# .github/workflows/trigger_deploy.yml

name: Trigger Deploy

on:
  push:
    branches:
      - main

jobs:
  decide_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine changes
        id: changes
        run: |
          CHANGED_FILES="bff/index.js"
          echo "Changed Files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Debug output
        run: |
          echo "Changed files output: ${{ steps.changes.outputs.changed_files }}"
          echo "App folder changed: ${{ contains(steps.changes.outputs.changed_files, 'app/') }}"
          echo "BFF folder changed: ${{ contains(steps.changes.outputs.changed_files, 'bff/') }}"
          echo "final output if: ${{ contains(steps.changes.outputs.changed_files, 'app/') || startsWith(steps.changes.outputs.changed_files, 'app/') }}"

      - name: Trigger app deployment
        if: ${{ contains(steps.changes.outputs.changed_files, 'app/') || startsWith(steps.changes.outputs.changed_files, 'app/') }}
        run: |
          echo "Listing files in .github/workflows/deploy:"
          ls -l ./deploy
          ls -l ../../.github/workflows/deploy
        uses: ../../.github/workflows/deploy/app_deploy.yml

      - name: Trigger bff deployment
        if: ${{ contains(steps.changes.outputs.changed_files, 'bff/') || startsWith(steps.changes.outputs.changed_files, 'bff/') }}
        uses: ../../.github/workflows/deploy/bff_deploy.yml
