# .github/workflows/trigger_deploy.yml

name: Trigger Deploy

on:
  push:
    branches:
      - main
      - *

jobs:
  decide_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine changes
        id: changes
        run: |
          # Fetch the latest commits to ensure we can compare
          git fetch origin

          # Determine the base commit for the comparison
          BASE_COMMIT=$(git merge-base origin/main HEAD)

          # Get the changed files between the base commit and the current commit
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)

          # Output the changed files
          echo "Changed Files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Debug output
        run: |
          echo "Changed files output: ${{ steps.changes.outputs.changed_files }}"
          echo "App folder changed: ${{ contains(steps.changes.outputs.changed_files, 'app/') }}"
          echo "BFF folder changed: ${{ contains(steps.changes.outputs.changed_files, 'bff/') }}"
          echo "Listing files in .github/workflows/deploy:"
          cat ./.github/workflows/deploy/bff_deploy.yml

      - name: Trigger app deployment
        if: ${{ contains(steps.changes.outputs.changed_files, 'app/') || startsWith(steps.changes.outputs.changed_files, 'app/') }}
        uses: ./.github/workflows/deploy/app_deploy.yml

      - name: Trigger bff deployment
        if: ${{ contains(steps.changes.outputs.changed_files, 'bff/') || startsWith(steps.changes.outputs.changed_files, 'bff/') }}
        uses: ./.github/workflows/deploy/bff_deploy.yml
